// Generated by CoffeeScript 1.6.3
var ApiController;

ApiController = (function() {
  function ApiController(app) {
    app.get("/api/test", this.test);
  }

  ApiController.prototype.test = function(req, res) {
    return res.json({
      name: 'Tinh',
      age: 22
    });
  };

  return ApiController;

})();

module.exports = ApiController;
